# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 688fa9bfc570bbcc57ef4ad41c3384b2757bd5f6f1e20a4dab853ae0d52d302b4c5a12a0548b1cef59c0cc9c03f6bea80558c0850e88d2fd30ad24308c1e1b9d

test:
  secret_key_base: 2a974effb5e84a845de0a3b1ceb104638278b8cd8e92b22774e8305237a918a7538a20c913095ca5d81af5eb4a630ba9e70ecf6befc2aa6a9214d556d6f8ef78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
